Repository DeveloperAcademy-POSTECH/2024-MacC-A16-AGAMI, pull requests merged in 2024-11, with the labels that each got.

#98 [#97] CollectionPlaceView에서 그림자 색상 변경
  AGAMI/Sources/Presentation/View/Map/CollectionPlaceView.swift
Labels: 🔨 refactor

#114 [#104] FirebaseService 수정
  AGAMI/Sources/Service/FirebaseService.swift
Labels: ✨ feat

#116 [#113] fetch 로직 수정
  AGAMI/Sources/App/AGAMIApp.swift
  AGAMI/Sources/Coordinator/PlakeCoordinator.swift
  AGAMI/Sources/Presentation/View/Home/HomeView.swift
  AGAMI/Sources/Presentation/View/Map/CollectionPlaceListView.swift
  AGAMI/Sources/Presentation/View/Plake/PlakeListView.swift
  AGAMI/Sources/Presentation/View/Search/SearchWritingView.swift
  AGAMI/Sources/Presentation/ViewModel/Plake/PlakeListViewModel.swift
  AGAMI/Sources/Presentation/ViewModel/Search/SearchShazamingViewModel.swift
  AGAMI/Sources/Service/FirebaseListenerService.swift
Labels: ✨ feat

#117 [hotfix / #99] 프로필 이미지 | 닉네임 수정
  AGAMI/Sources/Presentation/View/Account/AccountView.swift
  AGAMI/Sources/Presentation/ViewModel/Account/AccountViewModel.swift
Labels: 🐞 fix

#119 [#118] Ver 1.0(1)
  Project.swift
Labels: 🌏 deploy

#156 [#155] PersistenceService 모델 추상화
  AGAMI/Sources/Presentation/Model/SwiftData/SwiftDataPlaylistModel.swift
  AGAMI/Sources/Presentation/ViewModel/Search/SearchStartViewModel.swift
  AGAMI/Sources/Service/Persistence/PersistenceService.swift
Labels: 🔨 refactor

#158 [#157] HapticService 구현
  AGAMI/Sources/Presentation/View/Home/HomeView.swift
  AGAMI/Sources/Presentation/View/Plake/PlakeListView.swift
  AGAMI/Sources/Presentation/View/Plake/PlakePlaylistView.swift
  AGAMI/Sources/Presentation/View/Search/SearchShazamingView.swift
  AGAMI/Sources/Presentation/ViewModel/Home/HomeViewModel.swift
  AGAMI/Sources/Presentation/ViewModel/Plake/PlakeListViewModel.swift
  AGAMI/Sources/Presentation/ViewModel/Plake/PlakePlaylistViewModel.swift
  AGAMI/Sources/Presentation/ViewModel/Search/SearchShazamingViewModel.swift
  AGAMI/Sources/Service/Haptic/HapticService.swift
  AGAMI/Sources/Service/Persistence/PersistenceService.swift
Labels: ✨ feat

#160 [#159] iOS17 isSignedIn 버그 픽스
  AGAMI/Sources/App/AGAMIApp.swift
  AGAMI/Sources/Presentation/View/App/AppContentView.swift
  AGAMI/Sources/Presentation/View/SignIn/SignInView.swift
Labels: 🐞 fix

#166 [#161] 인스타그램 스토리 공유 UI 및 로직 구현
  AGAMI/Resources/Assets.xcassets/sharePhotoHolder.imageset/Contents.json
  AGAMI/Resources/Assets.xcassets/sharePhotoHolder.imageset/sharePhotoHolder.png
  AGAMI/Resources/Assets.xcassets/sharePhotoHolder.imageset/sharePhotoHolder@2x.png
  AGAMI/Resources/Assets.xcassets/sharePhotoHolder.imageset/sharePhotoHolder@3x.png
  AGAMI/Sources/Extensions/UIImage+.swift
  AGAMI/Sources/Extensions/View+.swift
  AGAMI/Sources/Presentation/View/Components/InstagramStickerView.swift
  AGAMI/Sources/Presentation/ViewModel/Plake/PlakePlaylistViewModel.swift
Labels: ✨ feat

#181 [#180] 버전 1.1.0 수정
  Project.swift
Labels: 🌏 deploy

#190 [#189] 코디네이터 빌드 시트에 AccountView 추가
  AGAMI/Sources/Coordinator/PlakeCoordinator.swift
Labels: 😩 chore

#191 [#177] SongDetail UI 구현
  AGAMI/Sources/Presentation/View/Plake/PlakePlaylistView.swift
  AGAMI/Sources/Presentation/ViewModel/Plake/PlakePlaylistViewModel.swift
Labels: ✨ feat

#202 [#196] plakeplaylistview 플레이스홀더 제거
  AGAMI/Resources/Assets.xcassets/sologPlaceholder.imageset/Contents.json
  AGAMI/Resources/Assets.xcassets/sologPlaceholder.imageset/sologPlaceholder.png
  AGAMI/Resources/Assets.xcassets/sologPlaceholder.imageset/sologPlaceholder@2x.png
  AGAMI/Resources/Assets.xcassets/sologPlaceholder.imageset/sologPlaceholder@3x.png
  AGAMI/Sources/Presentation/View/Components/InstagramStickerView.swift
  AGAMI/Sources/Presentation/View/Map/CollectionPlaceView.swift
  AGAMI/Sources/Presentation/View/Map/MKMapViewWrapper.swift
  AGAMI/Sources/Presentation/View/Plake/PlakeListView.swift
  AGAMI/Sources/Presentation/View/Plake/PlakePlaylistView.swift
  AGAMI/Sources/Presentation/View/Plake/SearchListView.swift
Labels: ✨ feat

#205 [#196] 업로드 플레이스홀더 버그 수정
  AGAMI/Sources/Presentation/View/Search/SearchWritingView.swift
Labels: ✨ feat

#224 [#219] Export Lottie 교체
  AGAMI/Resources/Assets.xcassets/SologImage/exportAppleMusic.imageset/Contents.json
  AGAMI/Resources/Assets.xcassets/SologImage/exportAppleMusic.imageset/exportAppleMusic.png
  AGAMI/Resources/Assets.xcassets/SologImage/exportAppleMusic.imageset/exportAppleMusic@2x.png
  AGAMI/Resources/Assets.xcassets/SologImage/exportAppleMusic.imageset/exportAppleMusic@3x.png
  AGAMI/Resources/Assets.xcassets/SologImage/exportSpotify.imageset/Contents.json
  AGAMI/Resources/Assets.xcassets/SologImage/exportSpotify.imageset/exportSpotify.png
  AGAMI/Resources/Assets.xcassets/SologImage/exportSpotify.imageset/exportSpotify@2x.png
  AGAMI/Resources/Assets.xcassets/SologImage/exportSpotify.imageset/exportSpotify@3x.png
  AGAMI/Resources/Lottie/applemusicLottie.json
  AGAMI/Resources/Lottie/exportLottie.json
  AGAMI/Resources/Lottie/spotifyLottie.json
  AGAMI/Sources/Helpers/LottieView.swift
  AGAMI/Sources/Presentation/View/Components/AppleMusicLottieView.swift
  AGAMI/Sources/Presentation/View/Components/SpotifyLottieView.swift
Labels: ✨ feat
